use_frameworks!

platform :ios, '11.0'

target 'NoMoreNetworkService_Example' do
  pod 'NoMoreNetworkService', :path => '../'

  target 'NoMoreNetworkService_Tests' do
    inherit! :search_paths

    
  end
end
